# melpazoid <https://github.com/riscy/melpazoid> build checks.

name: melpazoid
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with: { python-version: 3.9 }
    - name: Install
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install emacs && emacs --version
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: (org-bulletproof :repo "pondersson/org-bulletproof" :fetcher github)
        EXIST_OK: false
      run: echo $GITHUB_REF && make -C ~/melpazoid
